direccion_index:
    path:     /
    defaults: { _controller: "crudBundle:direccion:index" }
    methods:  GET

direccion_show:
    path:     /{id}/show
    defaults: { _controller: "crudBundle:direccion:show" }
    methods:  GET

direccion_new:
    path:     /new
    defaults: { _controller: "crudBundle:direccion:new" }
    methods:  [GET, POST]

direccion_edit:
    path:     /{id}/edit
    defaults: { _controller: "crudBundle:direccion:edit" }
    methods:  [GET, POST]

direccion_delete:
    path:     /{id}/delete
    defaults: { _controller: "crudBundle:direccion:delete" }
    methods:  DELETE
