usuario_index:
    path:     /
    defaults: { _controller: "crudBundle:usuario:index" }
    methods:  GET

usuario_show:
    path:     /{id}/show
    defaults: { _controller: "crudBundle:usuario:show" }
    methods:  GET

usuario_new:
    path:     /new
    defaults: { _controller: "crudBundle:usuario:new" }
    methods:  [GET, POST]

usuario_edit:
    path:     /{id}/edit
    defaults: { _controller: "crudBundle:usuario:edit" }
    methods:  [GET, POST]

usuario_delete:
    path:     /{id}/delete
    defaults: { _controller: "crudBundle:usuario:delete" }
    methods:  DELETE
