<?php

namespace crudBundle\Repository;

/**
 * direccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class direccionRepository extends \Doctrine\ORM\EntityRepository
{
}
